CREATE TABLE AuditRecord (
	AuditRecordId	UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	CreateDate		DateTime NOT NULL,
	UserId			UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_AuditRecord_UserId FOREIGN KEY REFERENCES AspNetUsers(Id),
	RecordId		UNIQUEIDENTIFIER NOT NULL,
	AuditType		VARCHAR(64) NOT NULL,
	RecordType		VARCHAR(64) NOT NULL,
	ChangedFields	NVARCHAR(max)
)