// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace t4mvc.scaffolding.templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class apimethodset : apimethodsetBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\nusing System.Collections.Generic;\nusing System.Linq;\nusing ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(".web.core;\nusing ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(".web.core.Infrastructure;\nusing ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(".web.core.Models;\nusing ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(".web.core.ViewModels;\nusing ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(".web.core.ViewModelServices;\nusing Microsoft.AspNetCore.Mvc;");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"

var constructorParams = string.Join(",", this.Entities.Select(x => "I" + x.Name + "ViewModelService " + x.Name.ToCamelCase() +"ViewModelService"));
            
            #line default
            #line hidden
            this.Write("\n\nnamespace ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName));
            
            #line default
            #line hidden
            this.Write(".web.Controllers\n{\n    public partial interface I");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName));
            
            #line default
            #line hidden
            this.Write("ApiController\n    {\n");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 foreach(var entity in this.Entities) { 
            
            #line default
            #line hidden
            this.Write("        DataTablesResultsBase Get");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("s(DataTablesRequestBase request, string cacheKey);\n");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n    }\n\n    [Route(\"api\")]\n\tpublic partial class ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName));
            
            #line default
            #line hidden
            this.Write("ApiController : t4mvcController, I");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName));
            
            #line default
            #line hidden
            this.Write("ApiController\n\t{\n        IServiceProvider serviceProvider;");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 foreach(var entity in this.Entities) { 
            
            #line default
            #line hidden
            this.Write("\n        I");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModelService ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModelService; ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\n\tpublic ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName));
            
            #line default
            #line hidden
            this.Write("ApiController(IServiceProvider serviceProvider, ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(constructorParams));
            
            #line default
            #line hidden
            this.Write(")\n    {\n        this.serviceProvider = serviceProvider;");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 foreach(var entity in this.Entities) { 
            
            #line default
            #line hidden
            this.Write("\n        this.");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModelService = ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModelService; ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n    }\n\n");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 foreach(var entity in this.Entities)
		{
		var entityName = entity.Name.ToSchemaName();
		var entityCamelCase = entityName.ToCamelCase(); 
            
            #line default
            #line hidden
            this.Write("\n        [Route(\"get");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityName.ToLowerCase()));
            
            #line default
            #line hidden
            this.Write("s\")]\n        public DataTablesResultsBase Get");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityName));
            
            #line default
            #line hidden
            this.Write("s(DataTablesRequestBase request, string cacheKey)\n        {\n            Current.S" +
                    "etDataTablesParameters(nameof(Get");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityName));
            
            #line default
            #line hidden
            this.Write("s), cacheKey, request);\n            var response = new DataTablesResultsBase() { " +
                    "draw = request.Draw };\n            var queryBase = ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityCamelCase));
            
            #line default
            #line hidden
            this.Write("ViewModelService.GetAll");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("();\n\n");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"

var searchableFields = entity.Fields.Where(x=> x.IsSearchable);
if (searchableFields.Count() > 0)
{
 
            
            #line default
            #line hidden
            this.Write("\n            if (request.Search != null && request.Search.Value != null)\n        " +
                    "    {\n                var s = request.Search.Value; ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 if (entity.HasIntSearchableFields) { 
            
            #line default
            #line hidden
            this.Write("\n                int i;\n                if (int.TryParse(s, out i))\n             " +
                    "   {\n                    queryBase = queryBase.Where(x => ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(" || ", searchableFields.Select(x => $"x.{(x.References == null ? (x.IsNumber ? x.Name.ToSchemaName() + " == i" : x.Name.ToSchemaName() + $".{x.SearchOperator}(s)") : x.Name.ToSchemaName() + x.References.NameField.Name.ToSchemaName() + $".{x.SearchOperator}(s)" )}"))));
            
            #line default
            #line hidden
            this.Write(");\n                }\n                else\n                {\n                    q" +
                    "ueryBase = queryBase.Where(x => ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(" || ", searchableFields.Where(x => !x.IsNumber).Select(x => $"x.{(x.References == null ? x.Name.ToSchemaName() : x.Name.ToSchemaName() + x.References.NameField.Name.ToSchemaName() )}.{x.SearchOperator}(s)"))));
            
            #line default
            #line hidden
            this.Write(");\n                }\n");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\n                queryBase = queryBase.Where(x => ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(" || ", searchableFields.Select(x => $"x.{(x.References == null ? x.Name.ToSchemaName() : x.Name.ToSchemaName() + x.References.NameField.Name.ToSchemaName() )}.{x.SearchOperator}(s)"))));
            
            #line default
            #line hidden
            this.Write(");\n");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n            }\n");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
            var query = queryBase.Sort(request)
                                 .Filter(request);

            var data = query.Skip(request.Start)
                            .Take(request.Length)
                            .ToList();

            var totalRecords            = queryBase.Count();
            response.recordsTotal       = totalRecords;
            response.recordsFiltered    = totalRecords;
            response.data               = data;

            return response;

        }

");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 if (entity.NameField != null) { 
            
            #line default
            #line hidden
            this.Write("\n        // Select2 field\n        [HttpGet]\n        [Route(\"select2/get");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityName.ToLowerCase()));
            
            #line default
            #line hidden
            this.Write("s\")]\n        public IEnumerable<");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityName));
            
            #line default
            #line hidden
            this.Write("ViewModel> Select2");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityName));
            
            #line default
            #line hidden
            this.Write("s(Select2SearchParameter searchParameter)\n        {\n            var records = ");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModelService.GetAll");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("();\n\n            if (searchParameter != null && searchParameter.Query != null)\n  " +
                    "          {\n                records = records.Where(x => x.");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.NameField.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(".StartsWith(searchParameter.Query));\n            }\n\n            return records.To" +
                    "List();\n        }\n");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n");
            
            #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\apimethodset.tt"
}
            
            #line default
            #line hidden
            this.Write("\n\n\t}\n}\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class apimethodsetBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
