// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace t4mvc.scaffolding.templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class dataservice : dataserviceBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using ");
            
            #line 5 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName));
            
            #line default
            #line hidden
            this.Write(".core;\r\nusing Microsoft.EntityFrameworkCore;\r\nusing System.Collections.Generic;\r\n" +
                    "using System.Linq;\r\n\r\nnamespace ");
            
            #line 10 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName));
            
            #line default
            #line hidden
            this.Write(".data.Services\r\n{\r\n    public partial interface I");
            
            #line 12 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("Service\r\n    {\r\n        ");
            
            #line 14 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write(" Find(params object[] keyValues);\r\n        IQueryable<");
            
            #line 15 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("> GetAll");
            
            #line 15 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("();\r\n        void Create");
            
            #line 16 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 16 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 16 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        void Update");
            
            #line 17 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 17 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 17 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", IEnumerable<string> ignore);\r\n\t\tvoid Delete");
            
            #line 18 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 18 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 18 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n\r\n    public partial class ");
            
            #line 21 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("Service : I");
            
            #line 21 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("Service\r\n    {\r\n        private readonly ");
            
            #line 23 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.DbContextName));
            
            #line default
            #line hidden
            this.Write(" context;\r\n        public ");
            
            #line 24 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("Service(");
            
            #line 24 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.DbContextName));
            
            #line default
            #line hidden
            this.Write(" dbContext)\r\n        {\r\n            this.context = dbContext;\r\n        }\r\n\r\n     " +
                    "   public void Create");
            
            #line 29 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 29 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 29 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 31 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
 if (this.Entity.EnableAuditing) { 
            
            #line default
            #line hidden
            this.Write("            // Auditing \r\n            var auditRecord     = ");
            
            #line 33 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".GetCreateAuditRecord(");
            
            #line 33 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 33 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.KeyField.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 33 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".CreateUserId);\r\n            this.context.AuditRecord.Add(auditRecord); \r\n\r\n");
            
            #line 36 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            this.context.");
            
            #line 37 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("s.Add(");
            
            #line 37 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        public ");
            
            #line 40 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write(" Find(params object[] keyValues)\r\n        {\r\n            return this.context.");
            
            #line 42 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("s.Find(keyValues);\r\n        }\r\n\r\n        public IQueryable<");
            
            #line 45 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("> GetAll");
            
            #line 45 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            return this.context.");
            
            #line 47 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("s.AsQueryable();\r\n        }\r\n\r\n        public void Update");
            
            #line 50 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 50 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 50 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", IEnumerable<string> ignore)\r\n        {\r\n");
            
            #line 52 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
 if (this.Entity.EnableAuditing) { 
            
            #line default
            #line hidden
            this.Write("            // Auditing \r\n            var oldRecord       = this.context.");
            
            #line 54 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("s.AsNoTracking().Single(x => x.");
            
            #line 54 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.KeyField.Name));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 54 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 54 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.KeyField.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n            var auditRecord     = oldRecord.GetUpdateAuditRecord(");
            
            #line 55 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", ignore);\r\n            this.context.AuditRecord.Add(auditRecord); \r\n\r\n");
            
            #line 58 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            this.context.");
            
            #line 59 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("s.Attach(");
            
            #line 59 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n            var entry       = this.context.Entry(");
            
            #line 61 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            entry.State     = EntityState.Modified;\r\n\r\n            foreach(va" +
                    "r prop in ignore)\r\n            {\r\n                entry.Property(prop).IsModifie" +
                    "d = false;\r\n            }\r\n        }\r\n\r\n\t\tpublic void Delete");
            
            #line 70 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 70 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 70 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 72 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
 if (this.Entity.EnableAuditing) { 
            
            #line default
            #line hidden
            this.Write("            // Auditing \r\n            var oldRecord       = this.context.");
            
            #line 74 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("s.AsNoTracking().Single(x => x.");
            
            #line 74 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.KeyField.Name));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 74 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 74 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.KeyField.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n            var auditRecord     = oldRecord.GetDeleteAuditRecord(");
            
            #line 75 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 75 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.KeyField.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 75 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".ModifyUserId);\r\n            this.context.AuditRecord.Add(auditRecord); \r\n\r\n");
            
            #line 78 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            this.context.");
            
            #line 79 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("s.Remove(");
            
            #line 79 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\dataservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n    }\r\n\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class dataserviceBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
