// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace t4mvc.scaffolding.templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class globalsearch : globalsearchBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using ");
            
            #line 6 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName));
            
            #line default
            #line hidden
            this.Write(".core;\r\nusing ");
            
            #line 7 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName));
            
            #line default
            #line hidden
            this.Write(".data.Services;\r\nusing ");
            
            #line 8 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName));
            
            #line default
            #line hidden
            this.Write(".web.core.Infrastructure;\r\nusing ");
            
            #line 9 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.ApplicationName));
            
            #line default
            #line hidden
            this.Write(@".web.core.ViewModels;


namespace t4mvc.web.core.ViewModelServices
{
    public interface ISearchViewModelServiceBase
    {
        GlobalSearchResult Search(string searchTerm);
        GlobalSearchResult SearchAll(string searchTerm);
    }
    public class SearchViewModelServiceBase : ISearchViewModelServiceBase
    {
");
            
            #line 21 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 foreach (var entity in this.SearchEntities) { 
            
            #line default
            #line hidden
            this.Write("        private readonly ");
            
            #line 22 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ServiceInterfaceTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 22 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ServiceInterfaceInstanceName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 23 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        public SearchViewModelServiceBase(");
            
            #line 25 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", this.SearchEntities.Select(x => $"{x.ServiceInterfaceTypeName} {x.ServiceInterfaceInstanceName}"))));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 27 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 foreach (var entity in this.SearchEntities) { 
            
            #line default
            #line hidden
            this.Write("            this.");
            
            #line 28 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ServiceInterfaceInstanceName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 28 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ServiceInterfaceInstanceName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 29 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"        }

        public GlobalSearchResult Search(string searchTerm)
        {
            return SearchInternal(searchTerm, 3);
        }

        public GlobalSearchResult SearchAll(string searchTerm)
        {
            return SearchInternal(searchTerm, null);
        }

        private GlobalSearchResult SearchInternal(string searchTerm, int? take = null)
        {
            if (string.IsNullOrWhiteSpace(searchTerm)) return new GlobalSearchResult();

            var rv              = new GlobalSearchResult();
            var requestor       = Current.UserId;
            bool isPossibleId   = Guid.TryParse(searchTerm, out Guid searchId);

");
            
            #line 50 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 foreach (var entity in this.SearchEntities) { 
            
            #line default
            #line hidden
            this.Write("            IQueryable<");
            
            #line 51 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SchemaName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 51 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.PluralCamelCaseName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 52 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n            if (isPossibleId)\r\n            {\r\n");
            
            #line 56 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 foreach (var entity in this.SearchEntities) { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 57 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.PluralCamelCaseName));
            
            #line default
            #line hidden
            this.Write("   = ");
            
            #line 57 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ServiceInterfaceInstanceName));
            
            #line default
            #line hidden
            this.Write(".GetAll");
            
            #line 57 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.PluralName));
            
            #line default
            #line hidden
            this.Write("().Where(x => x.");
            
            #line 57 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.KeyField.Name));
            
            #line default
            #line hidden
            this.Write(" == searchId);\r\n");
            
            #line 58 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n            else\r\n            {\r\n");
            
            #line 62 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 foreach (var entity in this.SearchEntities) { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 63 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.PluralCamelCaseName));
            
            #line default
            #line hidden
            this.Write("   = ");
            
            #line 63 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ServiceInterfaceInstanceName));
            
            #line default
            #line hidden
            this.Write(".GetAll");
            
            #line 63 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.PluralName));
            
            #line default
            #line hidden
            this.Write("().Where(x => ");
            
            #line 63 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(" || ", entity.SearchableFields.Select(x => $"x.{(x.References == null ? x.SchemaName : x.Name.ToSchemaName() + x.References.NameField.Name.ToSchemaName() )}.{x.SearchOperator}(searchTerm)"))));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 64 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n\r\n            if (take.HasValue)\r\n            {\r\n");
            
            #line 69 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 foreach (var entity in this.SearchEntities) { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 70 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.PluralCamelCaseName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 70 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.PluralCamelCaseName));
            
            #line default
            #line hidden
            this.Write(".Take(take.Value);\r\n");
            
            #line 71 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n\r\n");
            
            #line 74 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 foreach (var entity in this.SearchEntities) { 
            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 75 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.PluralCamelCaseName));
            
            #line default
            #line hidden
            this.Write(".Any())\r\n            {\r\n                rv.Categories.Add(new SearchResultCategor" +
                    "y\r\n                {\r\n                    Name    = \"");
            
            #line 79 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SchemaName));
            
            #line default
            #line hidden
            this.Write("\",\r\n                    Icon    = \"");
            
            #line 80 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.HtmlIcon.Replace("\"", "\\\"")));
            
            #line default
            #line hidden
            this.Write("\",\r\n                    Results = ");
            
            #line 81 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.PluralCamelCaseName));
            
            #line default
            #line hidden
            this.Write(".AsEnumerable().Select(x => new SearchResultItem { Title = $\"{x.");
            
            #line 81 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.NameField.SchemaName));
            
            #line default
            #line hidden
            this.Write("}\", Url = \"");
            
            #line 81 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.DetailsUrl));
            
            #line default
            #line hidden
            this.Write("\" + x.");
            
            #line 81 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.KeyField.Name));
            
            #line default
            #line hidden
            this.Write(" }).ToList()\r\n                });\r\n            }\r\n\r\n");
            
            #line 85 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\globalsearch.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            return rv;\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class globalsearchBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
