// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace t4mvc.scaffolding.templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class viewmodelservice : viewmodelserviceBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 5 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 var applicationName = Settings.ApplicationName.ToSchemaName(); 
            
            #line default
            #line hidden
            this.Write("using AutoMapper;\r\nusing ");
            
            #line 7 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(applicationName));
            
            #line default
            #line hidden
            this.Write(".core;\r\nusing ");
            
            #line 8 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(applicationName));
            
            #line default
            #line hidden
            this.Write(".data.services;\r\nusing ");
            
            #line 9 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(applicationName));
            
            #line default
            #line hidden
            this.Write(".web.core;\r\nusing ");
            
            #line 10 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(applicationName));
            
            #line default
            #line hidden
            this.Write(".web.core.Infrastructure;\r\nusing ");
            
            #line 11 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(applicationName));
            
            #line default
            #line hidden
            this.Write(".web.core.viewmodels;\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing Sy" +
                    "stem.Linq;\r\n\r\nnamespace ");
            
            #line 16 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(applicationName));
            
            #line default
            #line hidden
            this.Write(".web.core.viewmodelservices\r\n{\r\n    public partial interface I");
            
            #line 18 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModelService\r\n    {\r\n\t    IQueryable<");
            
            #line 20 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel> GetAll");
            
            #line 20 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("();\r\n        ");
            
            #line 21 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel Find(");
            
            #line 21 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.KeyField.DataType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 21 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Id);\r\n        void Create");
            
            #line 22 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 22 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 22 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel);\r\n        void Save");
            
            #line 23 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 23 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 23 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel);\r\n\t\tvoid Delete");
            
            #line 24 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 24 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 24 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel);\r\n\t\tvoid Hydrate(");
            
            #line 25 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 25 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel);\r\n");
            
            #line 26 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 foreach(var childTable in this.Entity.ChildReferences) { 
            
            #line default
            #line hidden
            this.Write("        List<");
            
            #line 27 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childTable.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel> Get");
            
            #line 27 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childTable.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("(Guid ");
            
            #line 27 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.KeyField.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 28 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n    }\r\n    public partial class ");
            
            #line 31 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModelService : I");
            
            #line 31 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModelService\r\n    {\r\n");
            
            #line 33 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"

foreach(var viewModelServiceDefinition in this.Entity.GetViewmModelServiceDefinitions()) { 
            
            #line default
            #line hidden
            this.Write("        private readonly ");
            
            #line 35 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModelServiceDefinition));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 36 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        private readonly IContextHelper contextHelper;\r\n        private readonly " +
                    "IUserService userService;\r\n\r\n        public IQueryable<");
            
            #line 40 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel> GetAll");
            
            #line 40 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n\t\t    var query = (from ");
            
            #line 42 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" in ");
            
            #line 42 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service.GetAll");
            
            #line 42 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("()\r\n                         ");
            
            #line 43 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 foreach (var childReference in this.Entity.Fields.Where(x => x.References != null)) { if (childReference.IsNullable) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t join ");
            
            #line 44 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 44 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name));
            
            #line default
            #line hidden
            this.Write(" in ");
            
            #line 44 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service.GetAll");
            
            #line 44 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("() on ");
            
            #line 44 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 44 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name));
            
            #line default
            #line hidden
            this.Write(" equals ");
            
            #line 44 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 44 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 44 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.KeyField.Name));
            
            #line default
            #line hidden
            this.Write(" into left_tmp_");
            
            #line 44 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 44 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t from left_");
            
            #line 45 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 45 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name));
            
            #line default
            #line hidden
            this.Write(" in left_tmp_");
            
            #line 45 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 45 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name));
            
            #line default
            #line hidden
            this.Write(".DefaultIfEmpty()\r\n\t\t\t\t\t\t ");
            
            #line 46 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
} else { 
            
            #line default
            #line hidden
            this.Write("                         join ");
            
            #line 47 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 47 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name));
            
            #line default
            #line hidden
            this.Write(" in ");
            
            #line 47 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service.GetAll");
            
            #line 47 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("() on ");
            
            #line 47 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 47 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name));
            
            #line default
            #line hidden
            this.Write(" equals ");
            
            #line 47 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 47 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 47 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.KeyField.Name));
            
            #line default
            #line hidden
            this.Write("\r\n                         ");
            
            #line 48 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 } }
            
            #line default
            #line hidden
            this.Write("\t\t\t             select new ");
            
            #line 49 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel\r\n\t\t\t\t\t\t {");
            
            #line 50 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 foreach(var field in this.Entity.Fields.Where(x => !x.IsAudit && !x.Secure)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 51 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 51 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 51 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t\t\t\t\t ");
            
            #line 52 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 } 
            
            #line default
            #line hidden
            
            #line 52 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 foreach (var childReference in this.Entity.Fields.Where(x => x.References != null)) { 
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 52 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name.ToSchemaName() + childReference.References.NameField.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 52 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((childReference.IsNullable ? "left_" : "" ) + childReference.References.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 52 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 52 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.NameField.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 52 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 }
            
            #line default
            #line hidden
            this.Write("});\r\n            return query;\r\n        }\r\n\r\n        public ");
            
            #line 56 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModelService(");
            
            #line 56 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.GetViewmModelServiceDefinitions().Any() ? string.Join(",", this.Entity.GetViewmModelServiceDefinitions()) + "," : ""));
            
            #line default
            #line hidden
            this.Write(" IUserService userService,\r\n                                            IContextH" +
                    "elper contextHelper)\r\n        {\r\n            this.");
            
            #line 59 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service = ");
            
            #line 59 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service;\r\n            this.contextHelper      = contextHelper;\r\n");
            
            #line 61 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 foreach(var svc in this.Entity.Fields.Where(x => x.References != null && !x.IsAudit).Select(x => $"{x.References.Name.ToCamelCase()}Service").Distinct()) { 
            
            #line default
            #line hidden
            this.Write("            this.");
            
            #line 62 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(svc));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 62 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(svc));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 63 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 } 
            
            #line default
            #line hidden
            
            #line 64 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 foreach(var childTable in this.Entity.ChildReferences.Where(x => x.Name != this.Entity.Name)) { 
            
            #line default
            #line hidden
            this.Write("            this.");
            
            #line 65 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childTable.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModelService = ");
            
            #line 65 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childTable.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModelService;\r\n");
            
            #line 66 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public void Create");
            
            #line 69 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 69 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 69 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel)\r\n        {\r\n            var ");
            
            #line 71 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 71 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel.Map<");
            
            #line 71 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n            ");
            
            #line 72 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 if (!this.Entity.RawData) { 
            
            #line default
            #line hidden
            
            #line 72 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".CreateDate = DateTime.Now;\r\n            ");
            
            #line 73 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".ModifyDate = DateTime.Now;\r\n            ");
            
            #line 74 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".CreateUserId = Current.UserId;\r\n            ");
            
            #line 75 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".ModifyUserId = Current.UserId;\r\n            ");
            
            #line 76 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 76 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("Id = Guid.NewGuid();\r\n\r\n");
            
            #line 78 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 78 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service.Create");
            
            #line 78 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 78 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n            contextHelper.SaveChanges();\r\n\r\n            // Set the new id b" +
                    "ack on the view so it can be called post-save\r\n            ");
            
            #line 83 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel.");
            
            #line 83 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("Id = ");
            
            #line 83 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 83 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("Id;\r\n        }\r\n\r\n        public ");
            
            #line 86 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel Find(");
            
            #line 86 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.KeyField.DataType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 86 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Id)\r\n        {\r\n            var ");
            
            #line 88 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 88 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service.Find(");
            
            #line 88 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Id)\r\n                                                  .Map<");
            
            #line 89 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel>();\r\n\r\n");
            
            #line 91 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 foreach(var field in this.Entity.Fields.Where(x => x.References != null && !x.IsAudit)) { 
            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 92 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 92 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n                ");
            
            #line 93 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 93 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToSchemaName() + field.References.NameField.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 93 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.References.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service.Find(");
            
            #line 93 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 93 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(")?.");
            
            #line 93 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.References.NameField.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 94 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            Hydrate(");
            
            #line 95 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n            return ");
            
            #line 96 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n\r\n        public void Save");
            
            #line 99 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 99 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 99 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel)\r\n        {\r\n            var ");
            
            #line 101 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 101 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel.Map<");
            
            #line 101 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n            ");
            
            #line 102 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 if (!this.Entity.RawData) {
            
            #line default
            #line hidden
            
            #line 102 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".ModifyDate = DateTime.Now;\r\n            ");
            
            #line 103 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".ModifyUserId = Current.UserId;\r\n\r\n");
            
            #line 105 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            var ignore = FieldMappingInspector<");
            
            #line 105 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write(">.GetAllReadonlyFields(");
            
            #line 105 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel);\r\n\r\n            ");
            
            #line 107 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service.Update");
            
            #line 107 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 107 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", ignore);\r\n\r\n            contextHelper.SaveChanges();\r\n        }\r\n\r\n\t\tpublic voi" +
                    "d Delete");
            
            #line 112 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 112 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 112 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel)\r\n        {\r\n            var ");
            
            #line 114 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 114 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel.Map<");
            
            #line 114 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n\r\n            ");
            
            #line 116 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service.Delete");
            
            #line 116 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 116 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n            contextHelper.SaveChanges();\r\n        }\r\n");
            
            #line 120 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 foreach (var childReference in this.Entity.Fields.Where(x => x.References != null)) { 
            
            #line default
            #line hidden
            this.Write("        public string Get");
            
            #line 120 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name.ToSchemaName() + childReference.References.NameField.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("(Guid? id)\r\n        {\r\n\t\t\treturn ");
            
            #line 122 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service.Find(id)?.");
            
            #line 122 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.References.NameField.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n");
            
            #line 124 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"

        } 
            
            #line default
            #line hidden
            this.Write("\r\n        public void Hydrate(");
            
            #line 127 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 127 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel)\r\n        {\r\n            var id = ");
            
            #line 129 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel.");
            
            #line 129 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("Id;\r\n        ");
            
            #line 130 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 if (this.Entity.Fields.Count(x => x.References != null) > 0) { foreach (var childReference in this.Entity.Fields.Where(x => x.References != null)) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 130 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel.");
            
            #line 130 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name.ToSchemaName() + childReference.References.NameField.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(" =     Get");
            
            #line 130 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name.ToSchemaName() + childReference.References.NameField.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 130 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel.");
            
            #line 130 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(");\r\n        ");
            
            #line 131 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"

} } 
            
            #line default
            #line hidden
            
            #line 132 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 if (this.Entity.ChildReferences.Count > 0) { foreach (var childReference in this.Entity.ChildReferences) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 132 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ViewModel.");
            
            #line 132 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.ParentFieldName));
            
            #line default
            #line hidden
            this.Write("=     Get");
            
            #line 132 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childReference.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("(id);\r\n        ");
            
            #line 133 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"

} } 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            
            #line 137 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 foreach(var childTable in this.Entity.ChildReferences) { 
            
            #line default
            #line hidden
            this.Write("        public List<");
            
            #line 138 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childTable.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel> Get");
            
            #line 138 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childTable.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("(Guid ");
            
            #line 138 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.KeyField.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return ");
            
            #line 140 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((childTable.Name == this.Entity.Name) ? "this" : childTable.Name.ToCamelCase() + "ViewModelService"));
            
            #line default
            #line hidden
            this.Write(".GetAll");
            
            #line 140 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childTable.PluralName.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write("()\r\n                        .Where(x => x.");
            
            #line 141 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(childTable.Field.Name.ToSchemaName()));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 141 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Entity.KeyField.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n                        .ToList();\r\n        }\r\n");
            
            #line 144 "C:\dev\git\t4mvc\scaffolding\t4mvc.scaffolding\templates\viewmodelservice.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class viewmodelserviceBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
